### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by brody192** [madebyjonny/payload-template#1]
Hey! just two simple suggestions for the template.
- For the `PAYLOAD_SECRET` variable's value, use a [template variable function](https://docs.railway.app/guides/create#template-variable-functions) like `${{secret(32)}}`
- For `DATABASE_URI` use the [private URL](https://docs.railway.app/guides/postgresql#private-networking) instead, like so `${{Postgres.DATABASE_PRIVATE_URL}}` 
this has the added benefits of being faster and the private network has no egress fees!

**Comment by jonny-kc** [comment]
Thanks for the feedback! 
Yeah I'll take a look at those, prob get those in tonight.

**Comment by jonny-kc** [comment]
I actually had time this morning, so i've made those amends, thanks again!

**Comment by madebyjonny** [comment]
hey @brody192  thanks for the feedback. I've made those  amends! 

Thanks again!
